### ISSUE TITLE
Can you help me solve the problem

### ISSUE THREAD

**Issue by gdjtyugegfg** [aevalenc/Centrifugal-Compressor-Preliminary-Design#5]
Hello, after I downloaded it, I ran the main function and I got an error: What should I do if the function or variable 'DesignStage' does not recognize。
![image](https://user-images.githubusercontent.com/40764159/222749969-17ecdab4-8a71-4f45-a97c-96fbcab958c9.png)

**Comment by gdjtyugegfg** [comment]
My email is cx072534@163.com.  Thank you very much!!!

**Comment by aevalenc** [comment]
Hello! Mmm I am not quite sure what you mean. Are you saying that you tried to run the program with a string other than `'Preliminary'`?

**Comment by gdjtyugegfg** [comment]
![image](https://user-images.githubusercontent.com/40764159/222890035-4a6879e7-a2fd-4fc2-a2af-fc16d0f03925.png)
emmmm,I don't know why the running program keeps reporting an error like this。

**Comment by aevalenc** [comment]
`DesignStage` and `varargin` are arguments to function main. The included README file has the instructions to use the function on the command window

**Comment by gdjtyugegfg** [comment]
Thank you!!!

**Comment by gdjtyugegfg** [comment]
Can I see the screenshot of your finished run？
